package core

import "time"

// Event represents a security event generated by an attack plugin.
// Every attack plugin produces events in this format.
// These events flow through the entire pipeline:
//
//	Plugin → Stream → Detection → Risk → Alert
type Event struct {
	// Unique identifier for this event
	ID string `json:"id"`

	// Type of event (e.g., "login_failed", "port_probe", "http_request")
	Type string `json:"event_type"`

	// Source IP address of the simulated attacker
	SourceIP string `json:"source_ip"`

	// Target of the attack (IP, hostname, or service URL)
	Target string `json:"target"`

	// Service being attacked (e.g., "auth-service", "web-server")
	Service string `json:"service"`

	// Username involved (if applicable, e.g., for brute force)
	User string `json:"user,omitempty"`

	// Additional data specific to the event type
	Metadata map[string]any `json:"metadata,omitempty"`

	// When this event occurred
	Timestamp time.Time `json:"timestamp"`

	// Which plugin generated this event
	PluginID string `json:"plugin_id"`

	// Which scenario this event belongs to (empty if standalone)
	ScenarioID string `json:"scenario_id,omitempty"`
}

// Severity levels for detection alerts
type Severity string

const (
	SeverityLow      Severity = "LOW"
	SeverityMedium   Severity = "MEDIUM"
	SeverityHigh     Severity = "HIGH"
	SeverityCritical Severity = "CRITICAL"
)

// Alert is generated when the detection engine finds suspicious activity.
type Alert struct {
	ID          string    `json:"id"`
	RuleName    string    `json:"rule_name"`
	Type        string    `json:"alert_type"`
	Description string    `json:"description"`
	Severity    Severity  `json:"severity"`
	SourceIP    string    `json:"source_ip"`
	Service     string    `json:"service,omitempty"`
	EventCount  int       `json:"event_count"`
	Timestamp   time.Time `json:"timestamp"`
	ScenarioID  string    `json:"scenario_id,omitempty"`
}

// ThreatLevel represents the overall threat assessment
type ThreatLevel string

const (
	ThreatLow      ThreatLevel = "LOW"
	ThreatMedium   ThreatLevel = "MEDIUM"
	ThreatHigh     ThreatLevel = "HIGH"
	ThreatCritical ThreatLevel = "CRITICAL"
)

// RiskScore represents the calculated risk for a source
type RiskScore struct {
	SourceIP    string      `json:"source_ip"`
	Score       int         `json:"score"`
	ThreatLevel ThreatLevel `json:"threat_level"`
	Factors     []string    `json:"factors"`
	UpdatedAt   time.Time   `json:"updated_at"`
}
