package core

import "context"

// EventSink is a function that receives events generated by a plugin.
// The plugin calls this function for each event it produces.
// The sink sends the event downstream (to the streaming layer).
type EventSink func(event Event) error

// Plugin is the interface that every attack plugin must implement.
//
// To create a new attack type, you implement this interface:
//
//	type MyAttackPlugin struct{}
//	func (p *MyAttackPlugin) ID() string            { return "my_attack" }
//	func (p *MyAttackPlugin) Name() string           { return "My Attack" }
//	func (p *MyAttackPlugin) Description() string    { return "Does something malicious" }
//	func (p *MyAttackPlugin) DefaultConfig() PluginConfig { return PluginConfig{...} }
//	func (p *MyAttackPlugin) Execute(ctx, config, sink) error { ... }
type Plugin interface {
	// ID returns a unique identifier for this plugin (e.g., "brute_force")
	ID() string

	// Name returns a human-readable name (e.g., "Brute Force Login Attack")
	Name() string

	// Description returns what this plugin simulates
	Description() string

	// DefaultConfig returns the default configuration for this plugin
	DefaultConfig() PluginConfig

	// Execute runs the attack simulation.
	// It generates events and sends them through the EventSink.
	// The context can be used to cancel the attack mid-run.
	Execute(ctx context.Context, config PluginConfig, sink EventSink) error
}

// PluginConfig holds configuration for a plugin execution
type PluginConfig struct {
	// Target IP or hostname to attack
	Target string `yaml:"target" json:"target"`

	// Target service name
	Service string `yaml:"service" json:"service"`

	// Source IP to simulate attacks from (randomized if empty)
	SourceIP string `yaml:"source_ip" json:"source_ip"`

	// How long the attack should run (e.g., "30s", "5m")
	Duration string `yaml:"duration" json:"duration"`

	// Attack intensity: events per second
	Rate int `yaml:"rate" json:"rate"`

	// Plugin-specific parameters
	Params map[string]any `yaml:"params" json:"params"`
}
